[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

[advisories]
version = 2
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
deny = [{ name = "chrono" }]
skip = [
    # Older version only used by examples/sniff
    { name = "bitflags", version = "=1.3.2" },
]
skip-tree = [{ crate = "windows-sys@0.48.0", reason = "the usual" }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-git = []

[sources.allow-org]
github = ["EmbarkStudios"]

[licenses]
version = 2
private = { ignore = true, registries = ["embark"] }
confidence-threshold = 0.92
allow = [
    "Apache-2.0",       # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
    "MIT",              # https://tldrlegal.com/license/mit-license
    "Unicode-DFS-2016",
]
exceptions = []
