
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
ignore = [
    # dev only xcb
    "RUSTSEC-2020-0097",
    "RUSTSEC-2021-0019",
]

[bans]
multiple-versions = "deny"
deny = [
]
skip = [
]
skip-tree = [
    # winit/glium/etc pull in a ridiculous amount of duplicates that I
    # really, REALLY don't care about, especially since they are for 1 example
    { name = "example-overlay" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-git = [
]

[sources.allow-org]
github = [
    "EmbarkStudios",
]

[licenses]
private = { ignore = true, registries = ["embark"] }
unlicensed = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.92
copyleft = "deny"
allow = [
    "Apache-2.0",   # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
    "BSD-3-Clause", # https://tldrlegal.com/license/bsd-3-clause-license-(revised)
    "MIT",          # https://tldrlegal.com/license/mit-license
]
exceptions = [
    { allow = ["ISC"], name = "libloading" },

    { allow = ["BSL-1.0"], name = "lazy-bytes-cast" },

    { allow = ["CC0-1.0"], name = "osmesa-sys" },
]
