
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
deny = [{ name = "chrono" }]
skip = [
    # insta/console uses outdated 0.42, but it's dev only so doesn't impact users
    { name = "windows-sys", version = "=0.42" },
    # Older version only used by examples/sniff
    { name = "bitflags", version = "=1.3.2" },
    # This will be fixed...eventually
    { name = "syn", version = "=1.0.109" },
]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
allow-git = []

[sources.allow-org]
github = ["EmbarkStudios"]

[licenses]
private = { ignore = true, registries = ["embark"] }
unlicensed = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.92
copyleft = "deny"
allow = [
    "Apache-2.0",       # https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
    "MIT",              # https://tldrlegal.com/license/mit-license
    "Unicode-DFS-2016",
]
exceptions = []
