[package]
name = "example-overlay"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
test = false
doctest = false

[dev-dependencies]
eframe = "0.12"
examples-shared = { path = "../../examples-shared" }
parking_lot = "0.11"
