[package]
name = "sniff"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"

[dependencies]
discord_game_sdk = { git = "https://github.com/EmbarkStudios/discord_game_sdk", rev = "464c31a" }
structopt = "0.3"
