[package]
name = "example-repl"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
test = false
doctest = false

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }
examples-shared = { path = "../../examples-shared" }
shell-words = "1.0"
