[package]
name = "example-repl"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
test = false
doctest = false

[dev-dependencies]
examples-shared = { path = "../../examples-shared" }
structopt = "0.3"
